# .pages.yml

media:
  input: public/images/uploads
  output: /images/uploads

content:
  - name: blog
    label: Blog Posts
    type: collection
    path: src/data/blog
    filename: "{year}/{slug}.md"

    view:
      primary: title
      sort: [ pubDatetime, title ]
      default:
        sort: pubDatetime
        order: desc

    fields:
      # --- path controls ---
      - name: year
        label: Year folder
        type: select
        options:
          values:
            - { label: "2023", value: "2023" }
            - { label: "2024", value: "2024" }
            - { label: "2025", value: "2025" }
            - { label: "2026", value: "2026" }
            - { label: "2027", value: "2027" }
            - { label: "2028", value: "2028" }
            - { label: "2029", value: "2029" }
            - { label: "2030", value: "2030" }

      - name: slug
        label: Slug (filename)
        type: string
        hint: "Lowercase with hyphens, no extension."

      # --- frontmatter (matches Astro schema) ---
      - { name: title,       label: Title,         type: string }
      - { name: description, label: Description,   type: text }
      - { name: author,      label: Author,        type: string, default: "Dzaki Azhari" }

      - name: pubDatetime
        label: Publish Date/Time
        type: date
        options: { time: true, format: "yyyy-MM-dd'T'HH:mm:ss'Z'" }

      - name: modDatetime
        label: Last Modified
        type: date
        options: { time: true, format: "yyyy-MM-dd'T'HH:mm:ss'Z'" }
        required: false

      - { name: featured,    label: Featured,      type: boolean, default: false }
      - { name: draft,       label: Draft,         type: boolean, default: false }

      # list of strings
      - { name: tags,        label: Tags,          type: text, list: true, default: [ "others" ] }

      # optionals
      - { name: ogImage,     label: OG Image,      type: image,  required: false }
      - { name: canonicalURL,label: Canonical URL, type: string, required: false }
      - { name: hideEditPost,label: Hide "Suggest Changes", type: boolean, default: false }
      - { name: timezone,    label: Timezone,      type: string, default: "Asia/Tokyo" }

      # body
      - { name: body,        label: Body,          type: markdown }
