site_label: "Unfold (Astro)"
branch: "main"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "src/data/blog"
    create: true
    path: "{{year}}/{{slug}}.md"
    extension: "md"
    format: "frontmatter"

    sort:
      field: "pubDatetime"
      order: "desc"

    media:
      assets: "public/images/uploads"
      public_path: "/images/uploads"

    fields:
      - { name: "year", label: "Year folder", widget: "select", options: ["2023", "2024", "2025", "2026"], default: "2025" }
      - { name: "slug", label: "Slug", widget: "string", hint: "Filename slug, lowercase with hyphens." }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "description", label: "Description", widget: "text" }
      - { name: "author", label: "Author", widget: "string", default: "Dzaki Azhari" }
      - { name: "pubDatetime", label: "Publish Date/Time", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ss[Z]" }
      - { name: "modDatetime", label: "Last Modified", widget: "datetime", required: false, format: "YYYY-MM-DDTHH:mm:ss[Z]" }
      - { name: "featured", label: "Featured", widget: "boolean", default: false }
      - { name: "draft", label: "Draft", widget: "boolean", default: false }
      - { name: "tags", label: "Tags", widget: "list", default: ["others"] }
      - { name: "ogImage", label: "OG Image", widget: "image", required: false }
      - { name: "canonicalURL", label: "Canonical URL", widget: "string", required: false }
      - { name: "hideEditPost", label: "Hide Edit Button", widget: "boolean", default: false }
      - { name: "timezone", label: "Timezone", widget: "string", default: "Asia/Tokyo" }
      - { name: "body", label: "Body", widget: "markdown" }

  - name: "pages"
    label: "Site Pages"
    folder: "src/pages"
    create: true
    path: "{{slug}}.mdx"
    extension: "mdx"
    format: "frontmatter"

    media:
      assets: "public/images/uploads"
      public_path: "/images/uploads"

    fields:
      - { name: "slug", label: "Slug", widget: "string", hint: "Filename without extension (e.g. 'about')" }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "description", label: "Description", widget: "text", required: false }
      - { name: "body", label: "Body", widget: "markdown" }
