# .pages.yml  (put this at the repo root)

# Where uploads live (repo) and how they are referenced (site URL path)
media:
  input: public/images/uploads
  output: /images/uploads   # served by Astro from /public

# Content types (collections & files)
content:
  # === BLOG POSTS ===
  - name: blog
    label: Blog Posts
    type: collection
    path: src/data/blog            # your posts root
    filename: "{year}/{slug}.md"   # subfolder by year
    view:
      primary: title
      sort: [ pubDatetime, title ]
      default:
        sort: pubDatetime
        order: desc
    fields:
      - { name: year, label: Year folder, type: select, options: [ "2023","2024","2025","2026" ], default: "2025" }
      - { name: slug, label: Slug (filename), type: string }
      - { name: title, label: Title, type: string }
      - { name: description, label: Description, type: text }
      - { name: author, label: Author, type: string, default: "Dzaki Azhari" }

      # Dates in your frontmatter (ISO-like with time)
      - name: pubDatetime
        label: Publish Date/Time
        type: date
        options: { time: true, format: "yyyy-MM-dd'T'HH:mm:ss'Z'" }  # date field options per docs
      - name: modDatetime
        label: Last Modified
        type: date
        options: { time: true, format: "yyyy-MM-dd'T'HH:mm:ss'Z'" }
        required: false

      - { name: featured, label: Featured, type: boolean, default: false }
      - { name: draft, label: Draft, type: boolean, default: false }
      - { name: tags, label: Tags, type: text, list: true, default: [ "others" ] }

      # Images & optional strings
      - { name: ogImage, label: OG Image, type: image, required: false }
      - { name: canonicalURL, label: Canonical URL, type: string, required: false }
      - { name: hideEditPost, label: Hide "Suggest Changes" Button, type: boolean, default: false }
      - { name: timezone, label: Timezone, type: string, default: "Asia/Tokyo" }

      # Body content editor
      - { name: body, label: Body, type: rich-text }  # WYSIWYG; supports images

  # === STATIC PAGES (MDX) ===
  - name: pages
    label: Site Pages
    type: collection
    path: src/pages
    filename: "{slug}.mdx"
    view:
      primary: title
      sort: [ title ]
    fields:
      - { name: slug, label: Slug (filename without extension), type: string }
      - { name: title, label: Title, type: string }
      - { name: description, label: Description, type: text, required: false }
      - { name: body, label: Body, type: rich-text }
