# .pages.yml

media:
  - name: uploads
    label: Post assets
    input: public/images/uploads
    output: /images/uploads
    categories: [image, document]
  - name: site-assets
    label: Site assets
    input: public/assets
    output: /assets
    categories: [image, code, document]

content:
  - name: blog
    label: Blog Posts
    description: "Long-form stories that surface on dzakiazhari.com. Paths and metadata map directly to src/content.config.ts."
    type: collection
    # Keep this path aligned with the Astro content collection defined in src/content.config.ts
    path: src/content/blog
    # Blog posts live in year-based folders; the CMS only needs the final slug segment here
    # Pages CMS uses moustache-style templating for field values.
    filename: "{{fields.year}}/{{fields.slug}}.md"
    exclude:
      - "**/_*/**"
      - "**/_*"
    subfolders: true

    view:
      layout: tree
      primary: title
      # Show the post title in the list, with date and tags alongside
      fields: [ title, pubDatetime, tags, draft ]
      sort: [ "pubDatetime desc", "title asc" ]
      search: [ title, description, tags ]
      default:
        sort: pubDatetime
        order: desc

    fields:
      # --- path controls ---
      - name: year
        label: Year folder
        type: select
        description: "Creates the folder segment under src/content/blog/{year}."
        default: "2025"
        options:
          placeholder: "Choose a year"
          creatable: true
          values:
            - { label: "2023", value: "2023" }
            - { label: "2024", value: "2024" }
            - { label: "2025", value: "2025" }
            - { label: "2026", value: "2026" }
            - { label: "2027", value: "2027" }
            - { label: "2028", value: "2028" }
            - { label: "2029", value: "2029" }
            - { label: "2030", value: "2030" }

      - name: slug
        label: Slug (filename)
        type: string
        description: "Lowercase with hyphens only. The CMS writes {slug}.md under the chosen year."
        required: true
        pattern:
          regex: "^[a-z0-9]+(?:-[a-z0-9]+)*$"
          message: "Use lowercase words separated by hyphens without the .md extension."

      # --- frontmatter (matches Astro schema) ---
      - name: title
        label: Title
        type: string
        description: "Displayed as the page <h1> and the document title tag."
        required: true

      - name: description
        label: Description
        type: text
        description: "Short summary for cards, RSS, and SEO meta tags."
        required: true
        options:
          maxlength: 180

      - name: author
        label: Author
        type: select
        default: "Dzaki Azhari"
        options:
          creatable: true
          placeholder: "Select or type an author"
          values:
            - { label: "Dzaki Azhari", value: "Dzaki Azhari" }

      - name: pubDatetime
        label: Publish date & time
        type: date
        options: { time: true, format: "yyyy-MM-dd'T'HH:mm:ss'Z'" }
        description: "Posts remain hidden until this timestamp (with a 15-minute grace window)."
        required: true

      - name: modDatetime
        label: Last modified
        type: date
        options: { time: true, format: "yyyy-MM-dd'T'HH:mm:ss'Z'" }
        required: false
        description: "Optional edit timestamp for changelog banners and structured data."

      - name: featured
        label: Featured
        type: boolean
        default: false
        description: "Mark true to pin on the homepage hero strip."

      - name: draft
        label: Draft
        type: boolean
        default: false
        description: "Drafts stay local and are excluded from builds and the RSS feed."

      - name: tags
        label: Tags
        type: select
        default: [ "others" ]
        options:
          multiple: true
          creatable: true
          placeholder: "Add topics like dev, blog, garden"
          values:
            - { label: "dev", value: "dev" }
            - { label: "blog", value: "blog" }
            - { label: "garden", value: "garden" }
            - { label: "life", value: "life" }
            - { label: "productivity", value: "productivity" }
            - { label: "notes", value: "notes" }
            - { label: "others", value: "others" }
        description: "Multi-select tags surface related content chips and search facets."

      # optionals
      - name: ogImage
        label: OG image
        type: image
        required: false
        description: "Uploads to /public/images/uploads. Leave blank to auto-generate dynamic OG art."
        options:
          media: uploads

      - name: canonicalURL
        label: Canonical URL
        type: string
        required: false
        description: "Use for cross-posts hosted elsewhere."
        pattern:
          regex: "^(https?:\\/\\/)([^\s]+)$"
          message: "Use an absolute URL starting with http:// or https://"

      - name: timezone
        label: Timezone
        type: string
        default: "Asia/Tokyo"
        description: "Overrides the global SITE.timezone for posts written elsewhere."

      # body
      - name: body
        label: Body
        type: markdown
        description: 'Write in Markdown. Supports callouts, code fences with file="" metadata, and remark-collapse toggles.'
