# .pages.yml

# Media settings (uploads go into repo under /public, served at /images/uploads)
media:
  input: public/images/uploads
  output: /images/uploads

# Content types
content:
  # === BLOG POSTS ===
  - name: blog
    label: Blog Posts
    type: collection
    path: src/data/blog              # your posts root
    filename: "{year}/{slug}.md"     # src/data/blog/<year>/<slug>.md

    view:
      primary: title
      sort: [ pubDatetime, title ]
      default:
        sort: pubDatetime
        order: desc

    fields:
      # --- path controls ---
      - name: year
        label: Year folder
        type: select
        options:
          - { label: "2023", value: "2023" }
          - { label: "2024", value: "2024" }
          - { label: "2025", value: "2025" }
          - { label: "2026", value: "2026" }
        default: "2025"

      - name: slug
        label: Slug (filename)
        type: string
        hint: "Lowercase with hyphens, no extension."

      # --- frontmatter (matches your Astro schema) ---
      - { name: title,        label: Title,                      type: string }
      - { name: description,  label: Description,                type: text }
      - { name: author,       label: Author,                     type: string, default: "Dzaki Azhari" }

      - name: pubDatetime
        label: Publish Date/Time
        type: date
        options: { time: true, format: "yyyy-MM-dd'T'HH:mm:ss'Z'" }

      - name: modDatetime
        label: Last Modified
        type: date
        options: { time: true, format: "yyyy-MM-dd'T'HH:mm:ss'Z'" }
        required: false

      - { name: featured,     label: Featured,                   type: boolean, default: false }
      - { name: draft,        label: Draft,                      type: boolean, default: false }

      # list of strings for tags
      - { name: tags,         label: Tags,                       type: text, list: true, default: [ "others" ] }

      # optional fields
      - { name: ogImage,      label: OG Image,                   type: image,  required: false }
      - { name: canonicalURL, label: Canonical URL,              type: string, required: false }
      - { name: hideEditPost, label: Hide "Suggest Changes",     type: boolean, default: false }
      - { name: timezone,     label: Timezone,                   type: string, default: "Asia/Tokyo" }

      # body content
      - { name: body,         label: Body,                       type: rich-text }
